name: Release
on:
  push:
    tags: ['v*']
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm package
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/nexa-nautax-*.zip
